ALTER TABLE club_books
MODIFY COLUMN read_date DATETIME;

ALTER TABLE users
MODIFY COLUMN firstname VARCHAR(100),
MODIFY COLUMN lastname VARCHAR(100);

ALTER TABLE clubs
MODIFY COLUMN name VARCHAR(50);